-- OPTIONAL SEED — not a migration. Nothing runs this for you.
--
-- Puts the two sample papers into the portal as real `tests` rows: the Word and
-- Excel practicals that used to exist only as TypeScript fixtures
-- (`src/exam/seedAttempt.ts`, `src/exam/excelSeedAttempt.ts`), which the exam
-- player still falls back to when no paper has been authored.
--
-- It lives in `db/seeds/` rather than `db/migrations/` because it is content,
-- not schema. A migration has to run on every database or the code breaks
-- against it; this is thirty questions of demo data that most databases have no
-- reason to want. See `db/seeds/README.md` for how to run it and when you would.
--
-- Generated from those fixtures rather than typed by hand, and checked on the
-- way out: the rows below rebuild both papers question for question.
--
-- Safe to run more than once, and safe on an empty database:
--   * no exam yet          -> does nothing, says so
--   * papers already there -> does nothing, says so
--   * otherwise            -> attaches them to the oldest exam
--
-- To undo:
--   DELETE FROM tests WHERE slug IN ('word-practical-sample', 'excel-practical-sample');
--   (test_questions cascades.)

DO $seed$
DECLARE
  target_exam uuid;
BEGIN
  SELECT id INTO target_exam FROM exams ORDER BY created_at LIMIT 1;

  IF target_exam IS NULL THEN
    RAISE NOTICE 'No exam exists yet — sample papers not seeded.';
    RETURN;
  END IF;

  IF EXISTS (SELECT 1 FROM tests WHERE slug IN ('word-practical-sample', 'excel-practical-sample')) THEN
    RAISE NOTICE 'Sample papers are already present — nothing to do.';
    RETURN;
  END IF;

  INSERT INTO tests
    (id, exam_id, name, slug, subject, description, section_name, tagline, duration_minutes, qualifying_marks, status)
  VALUES
    ('ae238f44-6cc5-48b7-a991-daf82ea70f79', target_exam, 'Word Practical — Sample Paper', 'word-practical-sample', 'word',
     'The original sample Word paper, seeded from the fixture it used to live in.',
     'Word Processing', 'Your Progress Brings You Closer to Success', 10, 13, 'published'),
    ('d6c49655-3d70-47bd-bc90-fca05effdffc', target_exam, 'Excel Practical — Sample Paper', 'excel-practical-sample', 'excel',
     'The original sample Excel paper, seeded from the fixture it used to live in.',
     'Spreadsheet', 'Your Progress Brings You Closer to Success', 15, 13, 'published');

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('93b82180-12d6-453f-aaa5-64c971a90fa9', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 1, 'word', 'Character Formatting', 'Easy', 4,
    'Make the paragraph bold and underline it.', 'पैराग्राफ को बोल्ड करें, अंडरलाइन करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'On the Home tab, in the Font group, click Bold (B).', 'Click Underline (U) in the same group.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Home टैब के Font ग्रुप में Bold (B) पर क्लिक करें।', 'उसी ग्रुप में Underline (U) पर क्लिक करें।']::text[],
    '{"subject":"word","lines":{"en":["The afternoon drifted quietly across the town, carrying warm air through half-open windows and stirring the pages of an unfinished notebook. Somewhere beyond the old market, a bicycle bell rang twice, followed by the distant sound of a bus turning around the corner. Nobody seemed to be in a hurry. A shopkeeper arranged blue bottles on a wooden shelf, while a curious cat watched from beneath a parked scooter. In the nearby park, children invented complicated rules for a game that had no name, arguing loudly before laughing and starting again. Above them, clouds gathered like scattered pieces of paper, changing shape whenever the wind moved. On a rooftop, someone watered a row of small plants and checked the sky with hopeful eyes. The city continued its ordinary rhythm: phones buzzed, doors opened, cups clinked, and footsteps crossed dusty sidewalks. Yet for a few minutes, everything felt strangely peaceful. Perhaps quiet moments are easier to notice when nothing important is expected to happen. A forgotten coin, a cracked sign, a yellow flower growing beside a wall—small things can become memorable when attention slows down. By evening, the streets would become brighter, louder, and busier, but for now the town simply breathed beneath the pale afternoon sun, waiting for whatever tomorrow decided to bring."],"hi":["The afternoon drifted quietly across the town, carrying warm air through half-open windows and stirring the pages of an unfinished notebook. Somewhere beyond the old market, a bicycle bell rang twice, followed by the distant sound of a bus turning around the corner. Nobody seemed to be in a hurry. A shopkeeper arranged blue bottles on a wooden shelf, while a curious cat watched from beneath a parked scooter. In the nearby park, children invented complicated rules for a game that had no name, arguing loudly before laughing and starting again. Above them, clouds gathered like scattered pieces of paper, changing shape whenever the wind moved. On a rooftop, someone watered a row of small plants and checked the sky with hopeful eyes. The city continued its ordinary rhythm: phones buzzed, doors opened, cups clinked, and footsteps crossed dusty sidewalks. Yet for a few minutes, everything felt strangely peaceful. Perhaps quiet moments are easier to notice when nothing important is expected to happen. A forgotten coin, a cracked sign, a yellow flower growing beside a wall—small things can become memorable when attention slows down. By evening, the streets would become brighter, louder, and busier, but for now the town simply breathed beneath the pale afternoon sun, waiting for whatever tomorrow decided to bring."]},"scope":"all"}'::jsonb, '[{"kind":"bold"},{"kind":"underline"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('cdb34609-e913-4d08-971e-b053d4129ae6', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 2, 'word', 'Text Highlight', 'Easy', 3,
    'Highlight the paragraph with green color.', 'पैराग्राफ को हरे रंग से हाइलाइट करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'In the Font group, open the arrow beside Text Highlight Colour.', 'Pick the bright green swatch — the second colour in the top row.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Font ग्रुप में Text Highlight Colour के बगल वाले तीर को खोलें।', 'चमकीला हरा स्वैच चुनें — ऊपर की पंक्ति का दूसरा रंग।']::text[],
    '{"subject":"word","lines":{"en":["Rain arrived without warning just after lunch, tapping softly against windows and turning the dusty road outside into a ribbon of silver. People hurried beneath umbrellas, while a few stood under shop awnings waiting for the clouds to pass. An old man carried a paper bag filled with vegetables, carefully balancing it beneath his coat. Across the street, a dog shook water from its fur and looked offended by the weather. Inside a small café, three friends continued their conversation as though the storm were part of the furniture. Steam rose from cups of tea, and someone played a quiet song from a phone near the counter. The rain became heavier for a while, covering every other sound in the neighborhood. Then, almost as suddenly as it had begun, it weakened. The clouds opened slightly, allowing a thin beam of sunlight to fall across the wet pavement. Cars moved again, bicycles appeared, and the street slowly returned to its usual rhythm. Nobody remembered exactly what they had been rushing toward, but everyone seemed happier to be moving again."],"hi":["Rain arrived without warning just after lunch, tapping softly against windows and turning the dusty road outside into a ribbon of silver. People hurried beneath umbrellas, while a few stood under shop awnings waiting for the clouds to pass. An old man carried a paper bag filled with vegetables, carefully balancing it beneath his coat. Across the street, a dog shook water from its fur and looked offended by the weather. Inside a small café, three friends continued their conversation as though the storm were part of the furniture. Steam rose from cups of tea, and someone played a quiet song from a phone near the counter. The rain became heavier for a while, covering every other sound in the neighborhood. Then, almost as suddenly as it had begun, it weakened. The clouds opened slightly, allowing a thin beam of sunlight to fall across the wet pavement. Cars moved again, bicycles appeared, and the street slowly returned to its usual rhythm. Nobody remembered exactly what they had been rushing toward, but everyone seemed happier to be moving again."]},"scope":"all"}'::jsonb, '[{"kind":"highlight","color":"#00ff00"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('d8f8568c-0aa5-4eb3-a7ce-862d5bc52c60', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 3, 'word', 'Font', 'Easy', 3,
    'Set the font of the paragraph to Times New Roman.', 'पैराग्राफ का फॉन्ट टाइम्स न्यू रोमन में सेट करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'Open the Font name box in the Font group.', 'Choose Times New Roman from the list.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Font ग्रुप में Font name बॉक्स खोलें।', 'सूची में से Times New Roman चुनें।']::text[],
    '{"subject":"word","lines":{"en":["At the edge of the village stood a wooden house with a green door and a garden full of plants that seemed determined to grow in every direction. Nobody knew exactly how old the house was, although the oldest residents claimed that their grandparents had played near it as children. Every morning, a woman named Mira opened the windows, swept the front steps, and placed a small bowl of water beside the gate for passing animals. Birds often landed on the fence, and occasionally a sleepy dog wandered into the garden and refused to leave. The house was quiet except for the ticking clock in the hallway and the occasional creak of the wooden floor. In the evenings, neighbors gathered outside to exchange stories about weather, crops, distant relatives, and strange things they had seen on the road. Nothing particularly exciting happened, yet nobody seemed disappointed. Life there moved according to familiar patterns, and those patterns gave ordinary days a comfortable shape. When the sun disappeared behind the hills, the garden became dark and still, while the green door reflected the warm glow of a lamp inside."],"hi":["At the edge of the village stood a wooden house with a green door and a garden full of plants that seemed determined to grow in every direction. Nobody knew exactly how old the house was, although the oldest residents claimed that their grandparents had played near it as children. Every morning, a woman named Mira opened the windows, swept the front steps, and placed a small bowl of water beside the gate for passing animals. Birds often landed on the fence, and occasionally a sleepy dog wandered into the garden and refused to leave. The house was quiet except for the ticking clock in the hallway and the occasional creak of the wooden floor. In the evenings, neighbors gathered outside to exchange stories about weather, crops, distant relatives, and strange things they had seen on the road. Nothing particularly exciting happened, yet nobody seemed disappointed. Life there moved according to familiar patterns, and those patterns gave ordinary days a comfortable shape. When the sun disappeared behind the hills, the garden became dark and still, while the green door reflected the warm glow of a lamp inside."]},"scope":"all"}'::jsonb, '[{"kind":"fontFamily","family":"Times New Roman"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('e5f8003d-0a8d-49d6-9b60-1cd5896b4341', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 4, 'word', 'Font Size', 'Medium', 3,
    'Set the font size of the paragraph to 15.', 'पैराग्राफ का फॉन्ट साइज 15 में सेट करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'Click inside the Font Size box in the Font group.', 'Type 15 and press Enter. 15 is not on the drop-down list, so it has to be typed.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Font ग्रुप के Font Size बॉक्स में क्लिक करें।', '15 टाइप करके Enter दबाएँ। 15 ड्रॉप-डाउन सूची में नहीं है, इसलिए इसे टाइप करना ज़रूरी है।']::text[],
    '{"subject":"word","lines":{"en":["The train station was almost empty when the clock reached seven. A cleaner pushed a cart slowly along the platform, humming a tune that disappeared beneath the noise of an arriving train. A young traveler sat on a bench with a backpack between his feet and a folded map in his hands. He had changed his destination three times already and still was not completely sure where he wanted to go. Across the tracks, a woman read a newspaper while drinking coffee from a paper cup. The loudspeaker announced a delay, followed by a second announcement correcting the first one. Nobody reacted with surprise. Trains, like people, apparently had their own ideas about schedules. After twenty minutes, the traveler stood, stretched his legs, and looked toward the dark end of the platform. A small light appeared in the distance and slowly grew brighter. The train arrived with a long metallic sigh. Doors opened, passengers stepped out, and others climbed aboard. For a moment, the station became crowded and noisy. Then the doors closed, the train moved away, and silence returned as if nothing had happened."],"hi":["The train station was almost empty when the clock reached seven. A cleaner pushed a cart slowly along the platform, humming a tune that disappeared beneath the noise of an arriving train. A young traveler sat on a bench with a backpack between his feet and a folded map in his hands. He had changed his destination three times already and still was not completely sure where he wanted to go. Across the tracks, a woman read a newspaper while drinking coffee from a paper cup. The loudspeaker announced a delay, followed by a second announcement correcting the first one. Nobody reacted with surprise. Trains, like people, apparently had their own ideas about schedules. After twenty minutes, the traveler stood, stretched his legs, and looked toward the dark end of the platform. A small light appeared in the distance and slowly grew brighter. The train arrived with a long metallic sigh. Doors opened, passengers stepped out, and others climbed aboard. For a moment, the station became crowded and noisy. Then the doors closed, the train moved away, and silence returned as if nothing had happened."]},"scope":"all"}'::jsonb, '[{"kind":"fontSize","size":15}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('6af55800-f744-4087-83b0-fe60e0b1df65', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 5, 'word', 'Paragraph Alignment', 'Easy', 3,
    'Apply center alignment to the paragraph.', 'पैराग्राफ में सेंटर अलाइनमेंट अप्लाई करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'On the Home tab, in the Paragraph group, click Center.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Home टैब के Paragraph ग्रुप में Center पर क्लिक करें।']::text[],
    '{"subject":"word","lines":{"en":["Somewhere in the middle of a crowded city was a narrow street that seemed to have been forgotten by modern time. The buildings were tall but slightly uneven, with balconies covered by plants and windows painted in colors that had faded over the years. A bakery occupied the corner, filling the street with the smell of fresh bread every morning. Next door was a tiny repair shop where the owner fixed watches, radios, lamps, and almost anything else people brought through the door. A handwritten sign in the window simply said, “If it can be repaired, bring it here.” Nobody knew whether the statement was completely true, but people liked the confidence behind it. At noon, delivery workers stopped for sandwiches, students bought pastries, and elderly residents sat on benches discussing the latest neighborhood rumors. By sunset, the street became quieter. Lights appeared behind curtains, the bakery closed its doors, and the repair shop owner finally turned off his desk lamp. The city remained noisy beyond the corner, but this little street seemed to exist at its own pace."],"hi":["Somewhere in the middle of a crowded city was a narrow street that seemed to have been forgotten by modern time. The buildings were tall but slightly uneven, with balconies covered by plants and windows painted in colors that had faded over the years. A bakery occupied the corner, filling the street with the smell of fresh bread every morning. Next door was a tiny repair shop where the owner fixed watches, radios, lamps, and almost anything else people brought through the door. A handwritten sign in the window simply said, “If it can be repaired, bring it here.” Nobody knew whether the statement was completely true, but people liked the confidence behind it. At noon, delivery workers stopped for sandwiches, students bought pastries, and elderly residents sat on benches discussing the latest neighborhood rumors. By sunset, the street became quieter. Lights appeared behind curtains, the bakery closed its doors, and the repair shop owner finally turned off his desk lamp. The city remained noisy beyond the corner, but this little street seemed to exist at its own pace."]},"scope":"all"}'::jsonb, '[{"kind":"align","align":"center"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('4f868c63-a848-4c69-823f-c08e298d99a3', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 6, 'word', 'Line Spacing', 'Medium', 4,
    'Set the line spacing of the paragraph to 2.0.', 'पैराग्राफ में लाइन स्पेसिंग 2.0 करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'In the Paragraph group, open the Line Spacing menu.', 'Choose 2.0.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Paragraph ग्रुप में Line Spacing मेन्यू खोलें।', '2.0 चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The notebook had been sitting inside the drawer for years, hidden beneath old receipts, broken pencils, and a collection of keys nobody could identify. Its cover was brown and scratched, with a tiny star drawn near one corner. When it was finally opened, the first few pages contained shopping lists and reminders about appointments. Later pages were filled with sketches, unfinished sentences, random numbers, and descriptions of places that no longer existed. There was a drawing of a house beside a lake, although nobody remembered owning a house near a lake. Another page described a blue bicycle, a red umbrella, and a mysterious bird that appeared every Thursday. The writing became less organized toward the end, but somehow more interesting. One sentence simply said, “Remember that ordinary days are not ordinary while they are happening.” The person reading it stopped for a moment. Outside, traffic moved along the road, someone laughed in the hallway, and a pressure cooker whistled in a nearby kitchen. Nothing unusual was happening. Yet the sentence made the familiar world feel slightly different, as though every small detail had been waiting quietly to be noticed."],"hi":["The notebook had been sitting inside the drawer for years, hidden beneath old receipts, broken pencils, and a collection of keys nobody could identify. Its cover was brown and scratched, with a tiny star drawn near one corner. When it was finally opened, the first few pages contained shopping lists and reminders about appointments. Later pages were filled with sketches, unfinished sentences, random numbers, and descriptions of places that no longer existed. There was a drawing of a house beside a lake, although nobody remembered owning a house near a lake. Another page described a blue bicycle, a red umbrella, and a mysterious bird that appeared every Thursday. The writing became less organized toward the end, but somehow more interesting. One sentence simply said, “Remember that ordinary days are not ordinary while they are happening.” The person reading it stopped for a moment. Outside, traffic moved along the road, someone laughed in the hallway, and a pressure cooker whistled in a nearby kitchen. Nothing unusual was happening. Yet the sentence made the familiar world feel slightly different, as though every small detail had been waiting quietly to be noticed."]},"scope":"all"}'::jsonb, '[{"kind":"lineHeight","value":2}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('ded78d11-7ac6-4e81-aeab-9425ff74369f', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 7, 'word', 'Paragraph Indent', 'Medium', 3,
    'Increase the indent level of the paragraph by one level.', 'पैराग्राफ के इंडेंट को एक लेवल बढ़ाएं।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'In the Paragraph group, click Increase Indent once.', 'One click is one level; a second click indents too far.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Paragraph ग्रुप में Increase Indent पर एक बार क्लिक करें।', 'एक क्लिक एक लेवल है; दूसरा क्लिक ज़्यादा इंडेंट कर देगा।']::text[],
    '{"subject":"word","lines":{"en":["The library closed at eight, but at seven fifty-five the building still contained a surprising amount of activity. Students hurried between shelves searching for final references, a professor typed notes at a corner desk, and two children whispered loudly enough to attract repeated warnings from their mother. Near the entrance, an old clock made a soft clicking sound every second. The librarian walked through the aisles, returning books to their places with the patience of someone who had performed the same task thousands of times. Outside, evening traffic had begun to glow beneath streetlights. Inside, the smell of paper and dust made the building feel separate from the city. At exactly eight, the librarian announced closing time. Chairs moved, bags were lifted, and books were carefully packed away. One student remained seated for a few extra seconds, staring at a page without reading it. Then she closed the book and smiled. She had not finished everything she planned to do, but perhaps that was acceptable. Some days were meant for completing tasks, while others were simply meant for making progress."],"hi":["The library closed at eight, but at seven fifty-five the building still contained a surprising amount of activity. Students hurried between shelves searching for final references, a professor typed notes at a corner desk, and two children whispered loudly enough to attract repeated warnings from their mother. Near the entrance, an old clock made a soft clicking sound every second. The librarian walked through the aisles, returning books to their places with the patience of someone who had performed the same task thousands of times. Outside, evening traffic had begun to glow beneath streetlights. Inside, the smell of paper and dust made the building feel separate from the city. At exactly eight, the librarian announced closing time. Chairs moved, bags were lifted, and books were carefully packed away. One student remained seated for a few extra seconds, staring at a page without reading it. Then she closed the book and smiled. She had not finished everything she planned to do, but perhaps that was acceptable. Some days were meant for completing tasks, while others were simply meant for making progress."]},"scope":"all"}'::jsonb, '[{"kind":"indent","levels":1}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('f97fa0c5-3c70-4389-b689-7afd4e43b7c3', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 8, 'word', 'Line Selection', 'Hard', 4,
    'Underline the 2nd line of the document.', 'डॉक्यूमेंट की 2वीं लाइन को अंडरलाइन करें।',
    ARRAY['Drag across the second line of the paragraph — the line that begins “had used it”.', 'In the Font group, click Underline (U).', 'Leave the rest of the passage untouched.']::text[], ARRAY['पैराग्राफ की दूसरी लाइन पर ड्रैग करें — वह लाइन जो “had used it” से शुरू होती है।', 'Font ग्रुप में Underline (U) पर क्लिक करें।', 'बाकी पैराग्राफ को वैसा ही छोड़ दें।']::text[],
    '{"subject":"word","lines":{"en":["A small boat rested on the shore, its wooden sides covered with layers of old paint. Nobody had used it since the previous summer, but every morning someone checked the ropes and moved it slightly above the reach of the waves. The sea was unusually calm that day. Far away, a group of birds moved together across the horizon, changing direction whenever the wind shifted. A boy walked along the beach collecting shells and pieces of smooth glass. He placed each discovery carefully into a blue bucket, although he had no plan for what to do with them later. His grandfather sat nearby beneath a faded umbrella and watched without saying much. Occasionally he pointed toward something floating in the water, and the boy would run closer to investigate. By afternoon, the bucket was nearly full. The boy looked at his collection proudly, then suddenly decided that he liked the beach better without it. One by one, he returned the shells to the sand. The glass pieces stayed in his pocket. Some things, he decided, were worth keeping."],"hi":["A small boat rested on the shore, its wooden sides covered with layers of old paint. Nobody had used it since the previous summer, but every morning someone checked the ropes and moved it slightly above the reach of the waves. The sea was unusually calm that day. Far away, a group of birds moved together across the horizon, changing direction whenever the wind shifted. A boy walked along the beach collecting shells and pieces of smooth glass. He placed each discovery carefully into a blue bucket, although he had no plan for what to do with them later. His grandfather sat nearby beneath a faded umbrella and watched without saying much. Occasionally he pointed toward something floating in the water, and the boy would run closer to investigate. By afternoon, the bucket was nearly full. The boy looked at his collection proudly, then suddenly decided that he liked the beach better without it. One by one, he returned the shells to the sand. The glass pieces stayed in his pocket. Some things, he decided, were worth keeping."]},"scope":{"from":92,"to":178}}'::jsonb, '[{"kind":"underline"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('f3506484-813f-49da-9512-80d183f43f03', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 9, 'word', 'Font Size', 'Easy', 3,
    'Set the font size of the paragraph to 8.', 'पैराग्राफ का फॉन्ट साइज 8 में सेट करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'Open the Font Size box in the Font group and choose 8.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Font ग्रुप में Font Size बॉक्स खोलकर 8 चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The train station was almost empty when the clock reached seven. A cleaner pushed a cart slowly along the platform, humming a tune that disappeared beneath the noise of an arriving train. A young traveler sat on a bench with a backpack between his feet and a folded map in his hands. He had changed his destination three times already and still was not completely sure where he wanted to go. Across the tracks, a woman read a newspaper while drinking coffee from a paper cup. The loudspeaker announced a delay, followed by a second announcement correcting the first one. Nobody reacted with surprise. Trains, like people, apparently had their own ideas about schedules. After twenty minutes, the traveler stood, stretched his legs, and looked toward the dark end of the platform. A small light appeared in the distance and slowly grew brighter. The train arrived with a long metallic sigh. Doors opened, passengers stepped out, and others climbed aboard. For a moment, the station became crowded and noisy. Then the doors closed, the train moved away, and silence returned as if nothing had happened."],"hi":["The train station was almost empty when the clock reached seven. A cleaner pushed a cart slowly along the platform, humming a tune that disappeared beneath the noise of an arriving train. A young traveler sat on a bench with a backpack between his feet and a folded map in his hands. He had changed his destination three times already and still was not completely sure where he wanted to go. Across the tracks, a woman read a newspaper while drinking coffee from a paper cup. The loudspeaker announced a delay, followed by a second announcement correcting the first one. Nobody reacted with surprise. Trains, like people, apparently had their own ideas about schedules. After twenty minutes, the traveler stood, stretched his legs, and looked toward the dark end of the platform. A small light appeared in the distance and slowly grew brighter. The train arrived with a long metallic sigh. Doors opened, passengers stepped out, and others climbed aboard. For a moment, the station became crowded and noisy. Then the doors closed, the train moved away, and silence returned as if nothing had happened."]},"scope":"all"}'::jsonb, '[{"kind":"fontSize","size":8}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('305d3c42-f50a-468a-9f62-0865e8d725a6', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 10, 'word', 'Paragraph Alignment', 'Easy', 3,
    'Apply justify alignment to the paragraph.', 'पैराग्राफ में justify अलाइनमेंट अप्लाई करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'On the Home tab, in the Paragraph group, click Justify.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Home टैब के Paragraph ग्रुप में Justify पर क्लिक करें।']::text[],
    '{"subject":"word","lines":{"en":["Somewhere in the middle of a crowded city was a narrow street that seemed to have been forgotten by modern time. The buildings were tall but slightly uneven, with balconies covered by plants and windows painted in colors that had faded over the years. A bakery occupied the corner, filling the street with the smell of fresh bread every morning. Next door was a tiny repair shop where the owner fixed watches, radios, lamps, and almost anything else people brought through the door. A handwritten sign in the window simply said, “If it can be repaired, bring it here.” Nobody knew whether the statement was completely true, but people liked the confidence behind it. At noon, delivery workers stopped for sandwiches, students bought pastries, and elderly residents sat on benches discussing the latest neighborhood rumors. By sunset, the street became quieter. Lights appeared behind curtains, the bakery closed its doors, and the repair shop owner finally turned off his desk lamp. The city remained noisy beyond the corner, but this little street seemed to exist at its own pace."],"hi":["Somewhere in the middle of a crowded city was a narrow street that seemed to have been forgotten by modern time. The buildings were tall but slightly uneven, with balconies covered by plants and windows painted in colors that had faded over the years. A bakery occupied the corner, filling the street with the smell of fresh bread every morning. Next door was a tiny repair shop where the owner fixed watches, radios, lamps, and almost anything else people brought through the door. A handwritten sign in the window simply said, “If it can be repaired, bring it here.” Nobody knew whether the statement was completely true, but people liked the confidence behind it. At noon, delivery workers stopped for sandwiches, students bought pastries, and elderly residents sat on benches discussing the latest neighborhood rumors. By sunset, the street became quieter. Lights appeared behind curtains, the bakery closed its doors, and the repair shop owner finally turned off his desk lamp. The city remained noisy beyond the corner, but this little street seemed to exist at its own pace."]},"scope":"all"}'::jsonb, '[{"kind":"align","align":"justify"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('af37aef4-5fcc-4239-be3c-256d5bde984d', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 11, 'word', 'Font', 'Easy', 3,
    'Set the font of the paragraph to Calibri.', 'पैराग्राफ का फॉन्ट Calibri में सेट करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'Open the Font name box in the Font group.', 'Choose Calibri. It has to be chosen, not left as the default.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Font ग्रुप में Font name बॉक्स खोलें।', 'Calibri चुनें। इसे चुनना ज़रूरी है, डिफ़ॉल्ट पर छोड़ना काफी नहीं है।']::text[],
    '{"subject":"word","lines":{"en":["At the edge of the village stood a wooden house with a green door and a garden full of plants that seemed determined to grow in every direction. Nobody knew exactly how old the house was, although the oldest residents claimed that their grandparents had played near it as children. Every morning, a woman named Mira opened the windows, swept the front steps, and placed a small bowl of water beside the gate for passing animals. Birds often landed on the fence, and occasionally a sleepy dog wandered into the garden and refused to leave. The house was quiet except for the ticking clock in the hallway and the occasional creak of the wooden floor. In the evenings, neighbors gathered outside to exchange stories about weather, crops, distant relatives, and strange things they had seen on the road. Nothing particularly exciting happened, yet nobody seemed disappointed. Life there moved according to familiar patterns, and those patterns gave ordinary days a comfortable shape. When the sun disappeared behind the hills, the garden became dark and still, while the green door reflected the warm glow of a lamp inside."],"hi":["At the edge of the village stood a wooden house with a green door and a garden full of plants that seemed determined to grow in every direction. Nobody knew exactly how old the house was, although the oldest residents claimed that their grandparents had played near it as children. Every morning, a woman named Mira opened the windows, swept the front steps, and placed a small bowl of water beside the gate for passing animals. Birds often landed on the fence, and occasionally a sleepy dog wandered into the garden and refused to leave. The house was quiet except for the ticking clock in the hallway and the occasional creak of the wooden floor. In the evenings, neighbors gathered outside to exchange stories about weather, crops, distant relatives, and strange things they had seen on the road. Nothing particularly exciting happened, yet nobody seemed disappointed. Life there moved according to familiar patterns, and those patterns gave ordinary days a comfortable shape. When the sun disappeared behind the hills, the garden became dark and still, while the green door reflected the warm glow of a lamp inside."]},"scope":"all"}'::jsonb, '[{"kind":"fontFamily","family":"Calibri"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('e83aa40a-d5b3-4ed8-8cd0-a2e3e62231bf', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 12, 'word', 'Character Formatting', 'Easy', 4,
    'Make the paragraph bold and italic it.', 'पैराग्राफ को बोल्ड करें, italic करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'On the Home tab, in the Font group, click Bold (B).', 'Click Italic (I) in the same group.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Home टैब के Font ग्रुप में Bold (B) पर क्लिक करें।', 'उसी ग्रुप में Italic (I) पर क्लिक करें।']::text[],
    '{"subject":"word","lines":{"en":["The afternoon drifted quietly across the town, carrying warm air through half-open windows and stirring the pages of an unfinished notebook. Somewhere beyond the old market, a bicycle bell rang twice, followed by the distant sound of a bus turning around the corner. Nobody seemed to be in a hurry. A shopkeeper arranged blue bottles on a wooden shelf, while a curious cat watched from beneath a parked scooter. In the nearby park, children invented complicated rules for a game that had no name, arguing loudly before laughing and starting again. Above them, clouds gathered like scattered pieces of paper, changing shape whenever the wind moved. On a rooftop, someone watered a row of small plants and checked the sky with hopeful eyes. The city continued its ordinary rhythm: phones buzzed, doors opened, cups clinked, and footsteps crossed dusty sidewalks. Yet for a few minutes, everything felt strangely peaceful. Perhaps quiet moments are easier to notice when nothing important is expected to happen. A forgotten coin, a cracked sign, a yellow flower growing beside a wall—small things can become memorable when attention slows down. By evening, the streets would become brighter, louder, and busier, but for now the town simply breathed beneath the pale afternoon sun, waiting for whatever tomorrow decided to bring."],"hi":["The afternoon drifted quietly across the town, carrying warm air through half-open windows and stirring the pages of an unfinished notebook. Somewhere beyond the old market, a bicycle bell rang twice, followed by the distant sound of a bus turning around the corner. Nobody seemed to be in a hurry. A shopkeeper arranged blue bottles on a wooden shelf, while a curious cat watched from beneath a parked scooter. In the nearby park, children invented complicated rules for a game that had no name, arguing loudly before laughing and starting again. Above them, clouds gathered like scattered pieces of paper, changing shape whenever the wind moved. On a rooftop, someone watered a row of small plants and checked the sky with hopeful eyes. The city continued its ordinary rhythm: phones buzzed, doors opened, cups clinked, and footsteps crossed dusty sidewalks. Yet for a few minutes, everything felt strangely peaceful. Perhaps quiet moments are easier to notice when nothing important is expected to happen. A forgotten coin, a cracked sign, a yellow flower growing beside a wall—small things can become memorable when attention slows down. By evening, the streets would become brighter, louder, and busier, but for now the town simply breathed beneath the pale afternoon sun, waiting for whatever tomorrow decided to bring."]},"scope":"all"}'::jsonb, '[{"kind":"bold"},{"kind":"italic"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('b1c3a35f-2921-4fbe-97e7-6507ca6021f5', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 13, 'word', 'Line Selection', 'Hard', 4,
    'Red colour highlight the 2nd line of the document.', 'डॉक्यूमेंट की 2वीं लाइन को red colour highlight करें।',
    ARRAY['Drag across the second line of the paragraph — the line that begins “had used it”.', 'In the Font group, open the arrow beside Text Highlight Colour.', 'Pick red — the first colour in the second row.']::text[], ARRAY['पैराग्राफ की दूसरी लाइन पर ड्रैग करें — वह लाइन जो “had used it” से शुरू होती है।', 'Font ग्रुप में Text Highlight Colour के बगल वाले तीर को खोलें।', 'लाल चुनें — दूसरी पंक्ति का पहला रंग।']::text[],
    '{"subject":"word","lines":{"en":["A small boat rested on the shore, its wooden sides covered with layers of old paint. Nobody had used it since the previous summer, but every morning someone checked the ropes and moved it slightly above the reach of the waves. The sea was unusually calm that day. Far away, a group of birds moved together across the horizon, changing direction whenever the wind shifted. A boy walked along the beach collecting shells and pieces of smooth glass. He placed each discovery carefully into a blue bucket, although he had no plan for what to do with them later. His grandfather sat nearby beneath a faded umbrella and watched without saying much. Occasionally he pointed toward something floating in the water, and the boy would run closer to investigate. By afternoon, the bucket was nearly full. The boy looked at his collection proudly, then suddenly decided that he liked the beach better without it. One by one, he returned the shells to the sand. The glass pieces stayed in his pocket. Some things, he decided, were worth keeping."],"hi":["A small boat rested on the shore, its wooden sides covered with layers of old paint. Nobody had used it since the previous summer, but every morning someone checked the ropes and moved it slightly above the reach of the waves. The sea was unusually calm that day. Far away, a group of birds moved together across the horizon, changing direction whenever the wind shifted. A boy walked along the beach collecting shells and pieces of smooth glass. He placed each discovery carefully into a blue bucket, although he had no plan for what to do with them later. His grandfather sat nearby beneath a faded umbrella and watched without saying much. Occasionally he pointed toward something floating in the water, and the boy would run closer to investigate. By afternoon, the bucket was nearly full. The boy looked at his collection proudly, then suddenly decided that he liked the beach better without it. One by one, he returned the shells to the sand. The glass pieces stayed in his pocket. Some things, he decided, were worth keeping."]},"scope":{"from":92,"to":178}}'::jsonb, '[{"kind":"highlight","color":"#ff0000"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('1b9c1b54-1b4d-4670-86fe-accf34300f00', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 14, 'word', 'Font Colour', 'Easy', 3,
    'Change the text colour of paragraph to Red.', 'पैराग्राफ के text को red colour करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'In the Font group, open the arrow beside Font Colour.', 'Pick red from the palette.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Font ग्रुप में Font Colour के बगल वाले तीर को खोलें।', 'पैलेट में से लाल चुनें।']::text[],
    '{"subject":"word","lines":{"en":["Rain arrived without warning just after lunch, tapping softly against windows and turning the dusty road outside into a ribbon of silver. People hurried beneath umbrellas, while a few stood under shop awnings waiting for the clouds to pass. An old man carried a paper bag filled with vegetables, carefully balancing it beneath his coat. Across the street, a dog shook water from its fur and looked offended by the weather. Inside a small café, three friends continued their conversation as though the storm were part of the furniture. Steam rose from cups of tea, and someone played a quiet song from a phone near the counter. The rain became heavier for a while, covering every other sound in the neighborhood. Then, almost as suddenly as it had begun, it weakened. The clouds opened slightly, allowing a thin beam of sunlight to fall across the wet pavement. Cars moved again, bicycles appeared, and the street slowly returned to its usual rhythm. Nobody remembered exactly what they had been rushing toward, but everyone seemed happier to be moving again."],"hi":["Rain arrived without warning just after lunch, tapping softly against windows and turning the dusty road outside into a ribbon of silver. People hurried beneath umbrellas, while a few stood under shop awnings waiting for the clouds to pass. An old man carried a paper bag filled with vegetables, carefully balancing it beneath his coat. Across the street, a dog shook water from its fur and looked offended by the weather. Inside a small café, three friends continued their conversation as though the storm were part of the furniture. Steam rose from cups of tea, and someone played a quiet song from a phone near the counter. The rain became heavier for a while, covering every other sound in the neighborhood. Then, almost as suddenly as it had begun, it weakened. The clouds opened slightly, allowing a thin beam of sunlight to fall across the wet pavement. Cars moved again, bicycles appeared, and the street slowly returned to its usual rhythm. Nobody remembered exactly what they had been rushing toward, but everyone seemed happier to be moving again."]},"scope":"all"}'::jsonb, '[{"kind":"fontColor","color":"#ff0000"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('53d44128-7f47-4e1b-b4af-06db58dc17d1', 'ae238f44-6cc5-48b7-a991-daf82ea70f79', 15, 'word', 'Character Formatting', 'Easy', 3,
    'Make the paragraph bold.', 'पैराग्राफ को बोल्ड करें।',
    ARRAY['Select the whole paragraph — drag across it, or click Select All in the Editing group.', 'On the Home tab, in the Font group, click Bold (B).', 'Apply nothing else — bold is the whole question.']::text[], ARRAY['पूरे पैराग्राफ को सेलेक्ट करें — उस पर ड्रैग करें, या Editing ग्रुप में Select All पर क्लिक करें।', 'Home टैब के Font ग्रुप में Bold (B) पर क्लिक करें।', 'और कुछ न लगाएँ — सवाल सिर्फ bold का है।']::text[],
    '{"subject":"word","lines":{"en":["The afternoon drifted quietly across the town, carrying warm air through half-open windows and stirring the pages of an unfinished notebook. Somewhere beyond the old market, a bicycle bell rang twice, followed by the distant sound of a bus turning around the corner. Nobody seemed to be in a hurry. A shopkeeper arranged blue bottles on a wooden shelf, while a curious cat watched from beneath a parked scooter. In the nearby park, children invented complicated rules for a game that had no name, arguing loudly before laughing and starting again. Above them, clouds gathered like scattered pieces of paper, changing shape whenever the wind moved. On a rooftop, someone watered a row of small plants and checked the sky with hopeful eyes. The city continued its ordinary rhythm: phones buzzed, doors opened, cups clinked, and footsteps crossed dusty sidewalks. Yet for a few minutes, everything felt strangely peaceful. Perhaps quiet moments are easier to notice when nothing important is expected to happen. A forgotten coin, a cracked sign, a yellow flower growing beside a wall—small things can become memorable when attention slows down. By evening, the streets would become brighter, louder, and busier, but for now the town simply breathed beneath the pale afternoon sun, waiting for whatever tomorrow decided to bring."],"hi":["The afternoon drifted quietly across the town, carrying warm air through half-open windows and stirring the pages of an unfinished notebook. Somewhere beyond the old market, a bicycle bell rang twice, followed by the distant sound of a bus turning around the corner. Nobody seemed to be in a hurry. A shopkeeper arranged blue bottles on a wooden shelf, while a curious cat watched from beneath a parked scooter. In the nearby park, children invented complicated rules for a game that had no name, arguing loudly before laughing and starting again. Above them, clouds gathered like scattered pieces of paper, changing shape whenever the wind moved. On a rooftop, someone watered a row of small plants and checked the sky with hopeful eyes. The city continued its ordinary rhythm: phones buzzed, doors opened, cups clinked, and footsteps crossed dusty sidewalks. Yet for a few minutes, everything felt strangely peaceful. Perhaps quiet moments are easier to notice when nothing important is expected to happen. A forgotten coin, a cracked sign, a yellow flower growing beside a wall—small things can become memorable when attention slows down. By evening, the streets would become brighter, louder, and busier, but for now the town simply breathed beneath the pale afternoon sun, waiting for whatever tomorrow decided to bring."]},"scope":"all"}'::jsonb, '[{"kind":"bold"}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('4bbc94a3-34a7-4f14-a593-1ad261f65f32', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 1, 'excel', 'Merge & Center', 'Easy', 3,
    'In the worksheet, merge and center the range A1:D1.', 'Worksheet में A1:D1 को Merge & Center करें।',
    ARRAY['Select the range A1:D1.', 'On the Home tab, in the Alignment group, click Merge & Center.']::text[], ARRAY['A1:D1 श्रेणी चुनें।', 'Home टैब के Alignment समूह में Merge & Center पर क्लिक करें।']::text[],
    '{"subject":"excel","grid":{"en":[["Student Enrollment Report"]],"hi":[["छात्र नामांकन रिपोर्ट"]]}}'::jsonb, '[{"kind":"merge","range":{"start":{"row":0,"col":0},"end":{"row":0,"col":3}},"centre":true}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('496519db-92f3-4f10-aac6-3a9dc31cbbb9', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 2, 'excel', 'Font & Font Size', 'Easy', 3,
    'Apply Calibri, 20 pt, Bold formatting to A1:D1.', 'A1:D1 पर Calibri, 20 pt और Bold लागू करें।',
    ARRAY['Select the range A1:D1.', 'On the Home tab, open the Font box and choose Calibri.', 'Open the Font Size box and choose 20.', 'Click Bold.']::text[], ARRAY['A1:D1 श्रेणी चुनें।', 'Home टैब में Font बॉक्स खोलकर Calibri चुनें।', 'Font Size बॉक्स खोलकर 20 चुनें।', 'Bold पर क्लिक करें।']::text[],
    '{"subject":"excel","grid":{"en":[["Employee Details"]],"hi":[["कर्मचारी विवरण"]]}}'::jsonb, '[{"kind":"style","range":{"start":{"row":0,"col":0},"end":{"row":0,"col":3}},"style":{"fontFamily":"Calibri","fontSize":20,"bold":true}}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('d6b0cbcb-4755-480f-9415-b27e000e477c', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 3, 'excel', 'Text Colour & Cell Background', 'Medium', 3,
    'For A2:D2, set the text colour to Dark Blue, the cell background to Yellow, the font size to 19 pt, and apply Italic.', 'A2:D2 में Text Color Dark Blue, Cell Background Yellow, Font Size 19 pt तथा Italic लागू करें।',
    ARRAY['Select the range A2:D2.', 'On the Home tab, click Font Color and choose Dark Blue.', 'Click Fill Color and choose Yellow.', 'Type 19 into the Font Size box.', 'Click Italic.']::text[], ARRAY['A2:D2 श्रेणी चुनें।', 'Home टैब में Font Color पर क्लिक कर Dark Blue चुनें।', 'Fill Color पर क्लिक कर Yellow चुनें।', 'Font Size बॉक्स में 19 लिखें।', 'Italic पर क्लिक करें।']::text[],
    '{"subject":"excel","grid":{"en":[["Employee Details","","",""],["Name","Department","Salary","Status"]],"hi":[["कर्मचारी विवरण","","",""],["नाम","विभाग","वेतन","स्थिति"]]}}'::jsonb, '[{"kind":"style","range":{"start":{"row":1,"col":0},"end":{"row":1,"col":3}},"style":{"fontColor":"#002060","fillColor":"#ffff00","fontSize":19,"italic":true}}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('ff520fb0-20d8-487e-9ffa-2692711d1ceb', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 4, 'excel', 'Outside Border', 'Medium', 3,
    'Apply an Outside Border to the range A1:D6.', 'A1:D6 Range पर Outside Border लगाएँ।',
    ARRAY['Select the range A1:D6.', 'On the Home tab, open Borders and choose Outside Borders.']::text[], ARRAY['A1:D6 श्रेणी चुनें।', 'Home टैब में Borders खोलकर Outside Borders चुनें।']::text[],
    '{"subject":"excel","grid":{"en":[["Student ID","Name","Course","Fee"],["101","Rahul","CCC","5000"],["102","Priya","DCA","7000"],["103","Amit","ADCA","10000"],["104","Neha","CCC","5000"],["105","Ravi","DCA","7000"]],"hi":[["छात्र आईडी","नाम","कोर्स","शुल्क"],["101","Rahul","CCC","5000"],["102","Priya","DCA","7000"],["103","Amit","ADCA","10000"],["104","Neha","CCC","5000"],["105","Ravi","DCA","7000"]]}}'::jsonb, '[{"kind":"outsideBorder","range":{"start":{"row":0,"col":0},"end":{"row":5,"col":3}}}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('9bbb72e4-f052-424e-9ff9-a26ad68b5eed', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 5, 'excel', 'Currency Format & Background', 'Medium', 3,
    'Apply Currency with no decimal places to D2:D6, and set the cell background to Orange.', 'D2:D6 को Currency (बिना Decimal) में Format करें तथा Cell Background Orange करें।',
    ARRAY['Select the range D2:D6.', 'On the Home tab, open the Number Format box and choose Currency (0 decimals).', 'Click Fill Color and choose Orange.']::text[], ARRAY['D2:D6 श्रेणी चुनें।', 'Home टैब में Number Format बॉक्स खोलकर Currency (0 decimals) चुनें।', 'Fill Color पर क्लिक कर Orange चुनें।']::text[],
    '{"subject":"excel","grid":{"en":[["ID","Name","Course","Fee"],["101","Rahul","CCC","5000"],["102","Priya","DCA","7000"],["103","Amit","ADCA","10000"],["104","Neha","CCC","5000"],["105","Ravi","DCA","7000"]],"hi":[["आईडी","नाम","कोर्स","शुल्क"],["101","Rahul","CCC","5000"],["102","Priya","DCA","7000"],["103","Amit","ADCA","10000"],["104","Neha","CCC","5000"],["105","Ravi","DCA","7000"]]}}'::jsonb, '[{"kind":"style","range":{"start":{"row":1,"col":3},"end":{"row":5,"col":3}},"style":{"numberFormat":"₹#,##0","fillColor":"#e36c0a"}}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('463f9818-b86e-4158-8f38-1b198f5c51b3', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 6, 'excel', 'Prefix', 'Easy', 3,
    'Add the prefix “STU1” before the values in A2:A6.', 'A2:A6 के प्रत्येक Data के पहले “STU1” Prefix लगाएँ।',
    ARRAY['Click cell A2 and type STU1101, then press Enter.', 'Repeat down to A6, or type STU1101 and STU1102 and drag the fill handle down.']::text[], ARRAY['सेल A2 पर क्लिक कर STU1101 लिखें और Enter दबाएँ।', 'A6 तक यही दोहराएँ, या STU1101 और STU1102 लिखकर Fill Handle नीचे खींचें।']::text[],
    '{"subject":"excel","grid":{"en":[["Student ID"],["101"],["102"],["103"],["104"],["105"]],"hi":[["छात्र आईडी"],["101"],["102"],["103"],["104"],["105"]]}}'::jsonb, '[{"kind":"values","cells":[{"row":1,"col":0,"value":"STU1101"},{"row":2,"col":0,"value":"STU1102"},{"row":3,"col":0,"value":"STU1103"},{"row":4,"col":0,"value":"STU1104"},{"row":5,"col":0,"value":"STU1105"}]}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('6011d255-b39f-4d62-93a2-172b828ec1b0', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 7, 'excel', 'CONCAT Formula', 'Hard', 4,
    'Use the CONCAT formula in D2:D6 to build the Full Name from the First Name and the Last Name.', 'D2:D6 में CONCAT Formula का उपयोग करके First Name और Last Name से Full Name निकालें।',
    ARRAY['Click cell D2.', 'Type =CONCAT(B2," ",C2) and press Enter.', 'Repeat for D3 to D6, or drag the fill handle down.']::text[], ARRAY['सेल D2 पर क्लिक करें।', '=CONCAT(B2," ",C2) लिखकर Enter दबाएँ।', 'D3 से D6 तक दोहराएँ, या Fill Handle नीचे खींचें।']::text[],
    '{"subject":"excel","grid":{"en":[["ID","First Name","Last Name","Full Name"],["101","Rahul","Sharma",""],["102","Priya","Verma",""],["103","Amit","Singh",""],["104","Neha","Gupta",""],["105","Ravi","Joshi",""]],"hi":[["आईडी","पहला नाम","उपनाम","पूरा नाम"],["101","Rahul","Sharma",""],["102","Priya","Verma",""],["103","Amit","Singh",""],["104","Neha","Gupta",""],["105","Ravi","Joshi",""]]}}'::jsonb, '[{"kind":"values","cells":[{"row":1,"col":3,"value":"Rahul Sharma","formula":"=CONCAT(B2,\" \",C2)"},{"row":2,"col":3,"value":"Priya Verma","formula":"=CONCAT(B3,\" \",C3)"},{"row":3,"col":3,"value":"Amit Singh","formula":"=CONCAT(B4,\" \",C4)"},{"row":4,"col":3,"value":"Neha Gupta","formula":"=CONCAT(B5,\" \",C5)"},{"row":5,"col":3,"value":"Ravi Joshi","formula":"=CONCAT(B6,\" \",C6)"}]}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('14ef99f9-fe8b-444f-ac38-bdaf3a8e84c2', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 8, 'excel', 'Due Fee Formula', 'Hard', 4,
    'Calculate the Due Fee in D2:D6 with a formula: Total Fee − Paid Fee.', 'D2:D6 में Formula का उपयोग करके Due Fee निकालें: Total Fee − Paid Fee।',
    ARRAY['Click cell D2.', 'Type =B2-C2 and press Enter.', 'Repeat for D3 to D6, or drag the fill handle down.']::text[], ARRAY['सेल D2 पर क्लिक करें।', '=B2-C2 लिखकर Enter दबाएँ।', 'D3 से D6 तक दोहराएँ, या Fill Handle नीचे खींचें।']::text[],
    '{"subject":"excel","grid":{"en":[["Student","Total Fee","Paid Fee","Due Fee"],["Rahul","5000","3500",""],["Priya","8000","6000",""],["Amit","5000","5000",""],["Neha","7000","4000",""],["Ravi","10000","7500",""]],"hi":[["छात्र","कुल शुल्क","जमा शुल्क","शेष शुल्क"],["Rahul","5000","3500",""],["Priya","8000","6000",""],["Amit","5000","5000",""],["Neha","7000","4000",""],["Ravi","10000","7500",""]]}}'::jsonb, '[{"kind":"values","cells":[{"row":1,"col":3,"value":1500,"formula":"=B2-C2"},{"row":2,"col":3,"value":2000,"formula":"=B3-C3"},{"row":3,"col":3,"value":0,"formula":"=B4-C4"},{"row":4,"col":3,"value":3000,"formula":"=B5-C5"},{"row":5,"col":3,"value":2500,"formula":"=B6-C6"}]}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('012d0e36-dfd7-48f8-87a0-13307246ad25', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 9, 'excel', 'Auto Fill Month', 'Medium', 4,
    'Auto Fill the month names in A3:A13 so the column reads Jan, Feb, Mar … Dec.', 'A3:A13 में Month Name को Auto Fill करें ताकि स्तंभ Jan, Feb, Mar … Dec पढ़े।',
    ARRAY['Click cell A2, which already reads Jan.', 'Drag the fill handle at its bottom-right corner down to A13.']::text[], ARRAY['सेल A2 पर क्लिक करें, जिसमें पहले से Jan लिखा है।', 'उसके नीचे-दाएँ कोने के Fill Handle को A13 तक खींचें।']::text[],
    '{"subject":"excel","grid":{"en":[["Month"],["Jan"]],"hi":[["माह"],["Jan"]]}}'::jsonb, '[{"kind":"values","cells":[{"row":2,"col":0,"value":"Feb"},{"row":3,"col":0,"value":"Mar"},{"row":4,"col":0,"value":"Apr"},{"row":5,"col":0,"value":"May"},{"row":6,"col":0,"value":"Jun"},{"row":7,"col":0,"value":"Jul"},{"row":8,"col":0,"value":"Aug"},{"row":9,"col":0,"value":"Sep"},{"row":10,"col":0,"value":"Oct"},{"row":11,"col":0,"value":"Nov"},{"row":12,"col":0,"value":"Dec"}]}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('4a10a669-98e8-41b5-9785-13dd957604bf', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 10, 'excel', 'Minimum Value', 'Medium', 4,
    'Use a formula in B8 to find the minimum value in B2:B6.', 'B8 में Formula का उपयोग करके B2:B6 का Minimum Value निकालें।',
    ARRAY['Click cell B8.', 'Type =MIN(B2:B6) and press Enter.']::text[], ARRAY['सेल B8 पर क्लिक करें।', '=MIN(B2:B6) लिखकर Enter दबाएँ।']::text[],
    '{"subject":"excel","grid":{"en":[["Student","Marks"],["Rahul","85"],["Priya","92"],["Amit","67"],["Neha","78"],["Ravi","88"],["",""],["Minimum Value",""]],"hi":[["छात्र","अंक"],["Rahul","85"],["Priya","92"],["Amit","67"],["Neha","78"],["Ravi","88"],["",""],["न्यूनतम मान",""]]}}'::jsonb, '[{"kind":"values","cells":[{"row":7,"col":1,"value":67,"formula":"=MIN(B2:B6)"}]}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('d613dcf7-7115-485f-9998-99569ae85f09', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 11, 'excel', 'Maximum Value', 'Medium', 4,
    'Use a formula in B8 to find the maximum value in B2:B6.', 'B8 में Formula का उपयोग करके B2:B6 का Maximum Value निकालें।',
    ARRAY['Click cell B8.', 'Type =MAX(B2:B6) and press Enter.']::text[], ARRAY['सेल B8 पर क्लिक करें।', '=MAX(B2:B6) लिखकर Enter दबाएँ।']::text[],
    '{"subject":"excel","grid":{"en":[["Student","Marks"],["Rahul","85"],["Priya","92"],["Amit","67"],["Neha","78"],["Ravi","88"],["",""],["Maximum Value",""]],"hi":[["छात्र","अंक"],["Rahul","85"],["Priya","92"],["Amit","67"],["Neha","78"],["Ravi","88"],["",""],["अधिकतम मान",""]]}}'::jsonb, '[{"kind":"values","cells":[{"row":7,"col":1,"value":92,"formula":"=MAX(B2:B6)"}]}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('90c2482e-1312-4ac2-8764-a5446b933be5', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 12, 'excel', 'Merge Across', 'Hard', 3,
    'Apply Merge Across to the range A1:D2.', 'A1:D2 Range पर Merge Across लागू करें।',
    ARRAY['Select the range A1:D2.', 'On the Home tab, in the Alignment group, click Merge Across.', 'Merge Across merges each row on its own, so A1:D1 and A2:D2 become two merged cells — not one.']::text[], ARRAY['A1:D2 श्रेणी चुनें।', 'Home टैब के Alignment समूह में Merge Across पर क्लिक करें।', 'Merge Across हर पंक्ति को अलग-अलग मर्ज करता है, इसलिए A1:D1 और A2:D2 दो अलग merged cell बनते हैं।']::text[],
    '{"subject":"excel","grid":{"en":[["Sales Report","","",""],["Monthly Sales","January","February","March"]],"hi":[["बिक्री रिपोर्ट","","",""],["मासिक बिक्री","जनवरी","फ़रवरी","मार्च"]]}}'::jsonb, '[{"kind":"merge","range":{"start":{"row":0,"col":0},"end":{"row":1,"col":3}},"across":true}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('8fd03c8f-1115-4f7a-8693-0312cb61de00', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 13, 'excel', 'Subscript Effect', 'Hard', 3,
    'For A1:E1, apply Merge & Center, apply the Subscript effect, and set the cell background to Yellow.', 'A1:E1 को Merge & Center करें, Subscript Effect लगाएँ तथा Cell Background Yellow करें।',
    ARRAY['Select the range A1:E1.', 'On the Home tab, click Merge & Center.', 'Click Subscript in the Font group.', 'Click Fill Color and choose Yellow.']::text[], ARRAY['A1:E1 श्रेणी चुनें।', 'Home टैब में Merge & Center पर क्लिक करें।', 'Font समूह में Subscript पर क्लिक करें।', 'Fill Color पर क्लिक कर Yellow चुनें।']::text[],
    '{"subject":"excel","grid":{"en":[["Employee Details"]],"hi":[["कर्मचारी विवरण"]]}}'::jsonb, '[{"kind":"merge","range":{"start":{"row":0,"col":0},"end":{"row":0,"col":4}},"centre":true},{"kind":"style","range":{"start":{"row":0,"col":0},"end":{"row":0,"col":4}},"style":{"textEffect":"subscript","fillColor":"#ffff00"}}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('ee7dea4a-8e58-487c-a2d6-903911ff0d30', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 14, 'excel', 'Worksheet Heading', 'Easy', 3,
    'The row and column headings are hidden on this sheet. Show them.', 'इस Sheet में Row व Column Heading छिपी हुई हैं। उन्हें Show करें।',
    ARRAY['On the View tab, in the Show group, tick Headings.', 'Page Layout ▸ Sheet Options ▸ Headings: View does the same thing.']::text[], ARRAY['View टैब के Show समूह में Headings चुनें।', 'Page Layout ▸ Sheet Options ▸ Headings: View से भी यही होता है।']::text[],
    '{"subject":"excel","grid":{"en":[["Sales Report","","",""],["January","February","March","April"],["25000","30000","28000","35000"]],"hi":[["बिक्री रिपोर्ट","","",""],["जनवरी","फ़रवरी","मार्च","अप्रैल"],["25000","30000","28000","35000"]]},"startingView":{"showGridlines":true,"showHeadings":false}}'::jsonb, '[{"kind":"view","showHeadings":true}]'::jsonb);

  INSERT INTO test_questions
    (id, test_id, position, subject, topic, difficulty, marks, instruction_en, instruction_hi, solution_en, solution_hi, content, operations)
  VALUES ('de46e5cc-0eb0-4b98-8114-e62c107994b0', 'd6c49655-3d70-47bd-bc90-fca05effdffc', 15, 'excel', 'Print Area', 'Hard', 3,
    'Set the print area to the Student Enrollment table in A1:D5, so the Month table in F1:G5 is left out of it.', 'Print Area को A1:D5 की Student Enrollment तालिका पर सेट करें, ताकि F1:G5 की Month तालिका उसमें न आए।',
    ARRAY['Select the range A1:D5.', 'On the Page Layout tab, in the Page Setup group, click Set Print Area.', 'A dashed outline appears around the print area.']::text[], ARRAY['A1:D5 श्रेणी चुनें।', 'Page Layout टैब के Page Setup समूह में Set Print Area पर क्लिक करें।', 'Print Area के चारों ओर एक बिंदुदार रेखा दिखाई देगी।']::text[],
    '{"subject":"excel","grid":{"en":[["Student ID","Name","Course","Fee","","Month","Value"],["STU101","Rahul","CCC","5000","","Jan","5000"],["STU102","Priya","DCA","7000","","Feb","7000"],["STU103","Amit","ADCA","10000","","Mar","10000"],["STU104","Neha","CCC","5000","","Apr","5000"]],"hi":[["छात्र आईडी","नाम","कोर्स","शुल्क","","माह","मान"],["STU101","Rahul","CCC","5000","","Jan","5000"],["STU102","Priya","DCA","7000","","Feb","7000"],["STU103","Amit","ADCA","10000","","Mar","10000"],["STU104","Neha","CCC","5000","","Apr","5000"]]}}'::jsonb, '[{"kind":"printArea","range":{"start":{"row":0,"col":0},"end":{"row":4,"col":3}}}]'::jsonb);
END
$seed$;
