-- Word Efficiency Tests 4 and 5.
--
-- Generated by `scripts/generateWordEfficiencyMigration.ts` from
-- `src/exam/papers/wordEfficiency.ts`, which is what `wordEfficiency.test.ts`
-- marks question by question. Edit the paper and regenerate; do not edit this
-- file by hand, or the papers that were tested and the papers that ship stop
-- being the same papers.
--
-- Idempotent: a re-run replaces both papers' questions rather than adding a
-- second copy, and leaves every other paper alone.
--
-- Statements are separated the way drizzle-kit separates them, with the marker
-- it splits a file on. Without those markers the whole file is sent as one
-- query, which node-postgres allows and other drivers do not — and a migration
-- that depends on the driver is a migration that works until it does not.
--
-- The marker is deliberately not written out in this comment: the split is a
-- plain string search, so a comment naming it is cut in half and its second
-- half is fed to Postgres as SQL. That is exactly what happened here once.

-- The papers hang off an exam, and which one decides what the mock list calls
-- them. The oldest *published* exam is the candidate-facing one, so that is
-- preferred; an unpublished one is used only when there is nothing else, and on
-- a fresh database one is created — published, or the papers would be listed
-- under an exam nobody can see.
INSERT INTO exams (id, name, slug, category, organiser_name, description, status)
SELECT
  gen_random_uuid(),
  'SSC CGL',
  'ssc-cgl',
  'SSC',
  'Staff Selection Commission',
  'Combined Graduate Level examination.',
  'published'
WHERE NOT EXISTS (SELECT 1 FROM exams);
--> statement-breakpoint

WITH host_exam AS (
  SELECT id
  FROM exams
  -- Published first, then oldest: false sorts before true, so this reads as
  -- "published before everything else" without naming the statuses twice.
  ORDER BY (status <> 'published'), created_at ASC
  LIMIT 1
),
upserted AS (
  INSERT INTO tests (
    id, exam_id, name, slug, subject, section_name, tagline, duration_minutes, qualifying_marks, status
  )
  VALUES
  (
    gen_random_uuid(),
    (SELECT id FROM host_exam),
    'Word Efficiency Test : 4',
    'word-efficiency-test-4',
    'word',
    'Word Processing',
    'Formatting drill on a district notice — replace, highlight, underline, indent.',
    20,
    10,
    'published'
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM host_exam),
    'Word Efficiency Test : 5',
    'word-efficiency-test-5',
    'word',
    'Word Processing',
    'Formatting drill on a company circular — effects, borders, spacing, lists.',
    20,
    10,
    'published'
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    section_name = EXCLUDED.section_name,
    tagline = EXCLUDED.tagline,
    duration_minutes = EXCLUDED.duration_minutes,
    qualifying_marks = EXCLUDED.qualifying_marks,
    status = EXCLUDED.status,
    updated_at = now()
  RETURNING id, slug
)
SELECT 1 FROM upserted;
--> statement-breakpoint

-- The questions are replaced wholesale: a paper's positions must run 1..n with
-- no gaps, and reconciling them one by one would leave a half-updated paper if
-- anything failed in the middle.
DELETE FROM test_questions
WHERE test_id IN (SELECT id FROM tests WHERE slug IN ('word-efficiency-test-4', 'word-efficiency-test-5'));
--> statement-breakpoint

WITH paper AS (SELECT id, slug FROM tests WHERE slug = 'word-efficiency-test-4')
INSERT INTO test_questions (
  id, test_id, position, subject, topic, difficulty, marks,
  instruction_en, instruction_hi, solution_en, solution_hi, content, operations
)
VALUES
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    1,
    'word',
    'Find and Replace, Font',
    'Hard',
    3,
    'Replace ''MSP'' with ''MRP'' wherever it appears in the document, then make it bold and give it a wavy underline.',
    'डॉक्यूमेंट में जहाँ भी ''MSP'' हो उसे ''MRP'' में बदलें, फिर उसे बोल्ड और वेव (wavy) अंडरलाइन करें।',
    ARRAY['Open Home → Replace, and replace MSP with MRP throughout.', 'Select each MRP and press Bold.', 'Open the Underline arrow and choose the wavy line.']::text[],
    ARRAY['होम → रिप्लेस खोलें और MSP को MRP से बदलें।', 'प्रत्येक MRP को चुनें और बोल्ड दबाएँ।', 'अंडरलाइन के तीर से वेव लाइन चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":"all","steps":[{"scope":"all","operations":[{"kind":"replaceText","find":"MSP","replacement":"MRP"}]},{"scope":{"select":"text","text":"MRP","occurrence":"all"},"operations":[{"kind":"bold"},{"kind":"underlineStyle","style":"wavy"}]}]}'::jsonb,
    '[{"kind":"replaceText","find":"MSP","replacement":"MRP"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    2,
    'word',
    'Font colour',
    'Medium',
    2,
    'Remove the blue colour from the text of the second paragraph.',
    'दूसरे पैराग्राफ के टेक्स्ट का नीला (blue) रंग दूर करें।',
    ARRAY['Select the second paragraph.', 'Open Font Colour and choose Automatic.']::text[],
    ARRAY['दूसरे पैराग्राफ को चुनें।', 'फ़ॉन्ट कलर खोलकर ऑटोमैटिक चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":2},"initial":[{"scope":{"select":"paragraph","index":2},"operations":[{"kind":"fontColor","color":"#0000ff"}]}]}'::jsonb,
    '[{"kind":"removeFontColor"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    3,
    'word',
    'Paragraph borders',
    'Medium',
    2,
    'Apply a bottom border to the fifth paragraph.',
    'पाँचवें पैराग्राफ पर नीचे (bottom) बॉर्डर लगाएँ।',
    ARRAY['Select the fifth paragraph.', 'Open the Borders menu and choose Bottom Border.']::text[],
    ARRAY['पाँचवें पैराग्राफ को चुनें।', 'बॉर्डर मेन्यू से बॉटम बॉर्डर चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":5}}'::jsonb,
    '[{"kind":"border","edge":"bottom"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    4,
    'word',
    'Font size',
    'Easy',
    1,
    'Set the font size of the fourth paragraph to 20 pt.',
    'चौथे पैराग्राफ की फ़ॉन्ट साइज़ 20pt सेट करें।',
    ARRAY['Select the fourth paragraph.', 'Type 20 in the font size box.']::text[],
    ARRAY['चौथे पैराग्राफ को चुनें।', 'फ़ॉन्ट साइज़ बॉक्स में 20 लिखें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":4}}'::jsonb,
    '[{"kind":"fontSize","size":20}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    5,
    'word',
    'Highlight',
    'Medium',
    2,
    'Highlight the first paragraph in any colour except yellow.',
    'पहले पैराग्राफ को किसी भी रंग से हाईलाइट करें, लेकिन पीले (yellow) रंग का उपयोग न करें।',
    ARRAY['Select the first paragraph.', 'Open Text Highlight Colour and pick any colour but yellow.']::text[],
    ARRAY['पहले पैराग्राफ को चुनें।', 'हाईलाइट कलर खोलें और पीले के अलावा कोई रंग चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":1}}'::jsonb,
    '[{"kind":"highlightAny","except":"#ffff00"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    6,
    'word',
    'Alignment',
    'Easy',
    1,
    'Centre the text of the first paragraph.',
    'पहले पैराग्राफ के टेक्स्ट को केंद्र (center) में संरेखित करें।',
    ARRAY['Select the first paragraph.', 'Press Center in the Paragraph group.']::text[],
    ARRAY['पहले पैराग्राफ को चुनें।', 'पैराग्राफ समूह में सेंटर दबाएँ।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":1}}'::jsonb,
    '[{"kind":"align","align":"center"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    7,
    'word',
    'Italic',
    'Easy',
    1,
    'Italicise the third paragraph.',
    'तीसरे पैराग्राफ को इटैलिक करें।',
    ARRAY['Select the third paragraph.', 'Press Italic.']::text[],
    ARRAY['तीसरे पैराग्राफ को चुनें।', 'इटैलिक दबाएँ।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":3}}'::jsonb,
    '[{"kind":"italic"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    8,
    'word',
    'Font colour',
    'Easy',
    1,
    'Set the font colour of the second paragraph to red.',
    'दूसरे पैराग्राफ के टेक्स्ट का रंग लाल (red) सेट करें।',
    ARRAY['Select the second paragraph.', 'Open Font Colour and choose red.']::text[],
    ARRAY['दूसरे पैराग्राफ को चुनें।', 'फ़ॉन्ट कलर से लाल रंग चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":2}}'::jsonb,
    '[{"kind":"fontColor","color":"#ff0000"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    9,
    'word',
    'Underline styles',
    'Medium',
    2,
    'Apply a wave underline to the fourth paragraph.',
    'चौथे पैराग्राफ को वेव अंडरलाइन (wave underline) करें।',
    ARRAY['Select the fourth paragraph.', 'Open the Underline arrow and choose the wavy line.']::text[],
    ARRAY['चौथे पैराग्राफ को चुनें।', 'अंडरलाइन के तीर से वेव लाइन चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":4}}'::jsonb,
    '[{"kind":"underlineStyle","style":"wavy"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    10,
    'word',
    'Alignment',
    'Easy',
    1,
    'Justify the third paragraph.',
    'तीसरे पैराग्राफ को जस्टिफ़ाई करें।',
    ARRAY['Select the third paragraph.', 'Press Justify.']::text[],
    ARRAY['तीसरे पैराग्राफ को चुनें।', 'जस्टिफ़ाई दबाएँ।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":3}}'::jsonb,
    '[{"kind":"align","align":"justify"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    11,
    'word',
    'Indentation',
    'Medium',
    2,
    'Give the second paragraph a left indent of 0.5 inches.',
    'दूसरे पैराग्राफ को 0.5 इंच का बायाँ इंडेंट दें।',
    ARRAY['Select the second paragraph.', 'Open the Paragraph dialog and set the left indent to 0.5".']::text[],
    ARRAY['दूसरे पैराग्राफ को चुनें।', 'पैराग्राफ डायलॉग में बायाँ इंडेंट 0.5" करें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":2}}'::jsonb,
    '[{"kind":"indentLeft","cm":0.5,"unit":"inch"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    12,
    'word',
    'Bold and underline',
    'Easy',
    2,
    'Make the fifth paragraph bold and underlined.',
    'पाँचवें पैराग्राफ के टेक्स्ट को बोल्ड और अंडरलाइन करें।',
    ARRAY['Select the fifth paragraph.', 'Press Bold, then Underline.']::text[],
    ARRAY['पाँचवें पैराग्राफ को चुनें।', 'बोल्ड दबाएँ, फिर अंडरलाइन।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":5}}'::jsonb,
    '[{"kind":"bold"},{"kind":"underline"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    13,
    'word',
    'Highlight',
    'Easy',
    1,
    'Highlight the third paragraph in teal.',
    'तीसरे पैराग्राफ को टील (teal) रंग से हाईलाइट करें।',
    ARRAY['Select the third paragraph.', 'Open Text Highlight Colour and choose teal.']::text[],
    ARRAY['तीसरे पैराग्राफ को चुनें।', 'हाईलाइट कलर से टील रंग चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":3}}'::jsonb,
    '[{"kind":"highlight","color":"#008080"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    14,
    'word',
    'Paragraph borders',
    'Medium',
    2,
    'Put a border on all four sides of the first paragraph.',
    'पहले पैराग्राफ के चारों ओर बॉर्डर लगाएँ।',
    ARRAY['Select the first paragraph.', 'Open the Borders menu and choose All Borders.']::text[],
    ARRAY['पहले पैराग्राफ को चुनें।', 'बॉर्डर मेन्यू से ऑल बॉर्डर चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":1}}'::jsonb,
    '[{"kind":"border","edge":"all"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-4'),
    15,
    'word',
    'Styles',
    'Medium',
    2,
    'Apply the Heading 1 style to the first paragraph.',
    'पहले पैराग्राफ पर हेडिंग 1 (Heading 1) स्टाइल लगाएँ।',
    ARRAY['Select the first paragraph.', 'Choose Heading 1 from the Styles gallery.']::text[],
    ARRAY['पहले पैराग्राफ को चुनें।', 'स्टाइल गैलरी से हेडिंग 1 चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The district office will publish the revised MSP schedule for every registered applicant this month.","Field officers must record the survey readings twice a day and file them with the zonal supervisor.","Any applicant whose MSP claim has changed must inform the help desk in writing before the last date.","The revised timetable will be displayed on the notice board outside the main gate of the office.","Late submissions are accepted only with a written explanation from the reporting officer concerned."],"hi":["जिला कार्यालय इस माह प्रत्येक पंजीकृत आवेदक के लिए संशोधित MSP सूची प्रकाशित करेगा।","क्षेत्रीय अधिकारी प्रतिदिन दो बार सर्वेक्षण रीडिंग दर्ज करेंगे और उन्हें पर्यवेक्षक को भेजेंगे।","जिस आवेदक का MSP दावा बदला है, वह अंतिम तिथि से पहले सहायता केंद्र को लिखित सूचना दे।","संशोधित समय-सारणी कार्यालय के मुख्य द्वार के बाहर सूचना पट पर प्रदर्शित की जाएगी।","विलंब से प्राप्त आवेदन केवल संबंधित रिपोर्टिंग अधिकारी के लिखित स्पष्टीकरण के साथ स्वीकार होंगे।"]},"scope":{"select":"paragraph","index":1}}'::jsonb,
    '[{"kind":"paragraphStyle","style":"Heading1"}]'::jsonb
  );

WITH paper AS (SELECT id, slug FROM tests WHERE slug = 'word-efficiency-test-5')
INSERT INTO test_questions (
  id, test_id, position, subject, topic, difficulty, marks,
  instruction_en, instruction_hi, solution_en, solution_hi, content, operations
)
VALUES
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    1,
    'word',
    'Subscript',
    'Medium',
    2,
    'Apply the subscript effect to the word ''Strategy'' wherever it appears in the document.',
    'डॉक्यूमेंट में जहाँ भी ''Strategy'' शब्द हो, उस पर सबस्क्रिप्ट प्रभाव लगाएँ।',
    ARRAY['Select each occurrence of Strategy.', 'Press Subscript in the Font group.']::text[],
    ARRAY['''Strategy'' के प्रत्येक रूप को चुनें।', 'फ़ॉन्ट समूह में सबस्क्रिप्ट दबाएँ।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"text","text":"Strategy","occurrence":"all"}}'::jsonb,
    '[{"kind":"subscript"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    2,
    'word',
    'Font family',
    'Easy',
    1,
    'Change the font of the second paragraph to ''Times New Roman''.',
    'दूसरे पैराग्राफ का फ़ॉन्ट ''Times New Roman'' में बदलें।',
    ARRAY['Select the second paragraph.', 'Choose Times New Roman in the font box.']::text[],
    ARRAY['दूसरे पैराग्राफ को चुनें।', 'फ़ॉन्ट बॉक्स में Times New Roman चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":2}}'::jsonb,
    '[{"kind":"fontFamily","family":"Times New Roman"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    3,
    'word',
    'Highlight',
    'Medium',
    2,
    'Remove the highlight from the third paragraph.',
    'तीसरे पैराग्राफ का हाईलाइट हटाएँ।',
    ARRAY['Select the third paragraph.', 'Open Text Highlight Colour and choose No Colour.']::text[],
    ARRAY['तीसरे पैराग्राफ को चुनें।', 'हाईलाइट कलर खोलकर नो कलर चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":3},"initial":[{"scope":{"select":"paragraph","index":3},"operations":[{"kind":"highlight","color":"#ffff00"}]}]}'::jsonb,
    '[{"kind":"removeHighlight"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    4,
    'word',
    'Alignment',
    'Easy',
    1,
    'Align the text in the fourth paragraph to the right.',
    'चौथे पैराग्राफ के टेक्स्ट को दाएँ (right) संरेखित करें।',
    ARRAY['Select the fourth paragraph.', 'Press Align Text Right.']::text[],
    ARRAY['चौथे पैराग्राफ को चुनें।', 'अलाइन टेक्स्ट राइट दबाएँ।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":4}}'::jsonb,
    '[{"kind":"align","align":"right"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    5,
    'word',
    'Underline styles',
    'Medium',
    2,
    'Apply a double underline to the word ''Innovation'' wherever it occurs.',
    'जहाँ भी ''Innovation'' शब्द आए, उस पर डबल अंडरलाइन लगाएँ।',
    ARRAY['Select each occurrence of Innovation.', 'Open the Underline arrow and choose the double line.']::text[],
    ARRAY['''Innovation'' के प्रत्येक रूप को चुनें।', 'अंडरलाइन के तीर से डबल लाइन चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"text","text":"Innovation","occurrence":"all"}}'::jsonb,
    '[{"kind":"underlineStyle","style":"double"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    6,
    'word',
    'Indentation',
    'Medium',
    2,
    'Set the left indent of the first paragraph to 1.1 inches.',
    'पहले पैराग्राफ का बायाँ इंडेंट 1.1 इंच सेट करें।',
    ARRAY['Select the first paragraph.', 'Open the Paragraph dialog and set the left indent to 1.1".']::text[],
    ARRAY['पहले पैराग्राफ को चुनें।', 'पैराग्राफ डायलॉग में बायाँ इंडेंट 1.1" करें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":1}}'::jsonb,
    '[{"kind":"indentLeft","cm":1.1,"unit":"inch"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    7,
    'word',
    'Paragraph spacing',
    'Medium',
    1,
    'Set 12 pt of space after the first paragraph.',
    'पहले पैराग्राफ के बाद 12pt स्थान (space after) सेट करें।',
    ARRAY['Select the first paragraph.', 'Open the Paragraph dialog and set Spacing After to 12 pt.']::text[],
    ARRAY['पहले पैराग्राफ को चुनें।', 'पैराग्राफ डायलॉग में आफ्टर 12pt करें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":1}}'::jsonb,
    '[{"kind":"spaceAfter","points":12}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    8,
    'word',
    'Paragraph borders',
    'Medium',
    1,
    'Apply an outside border to the second paragraph.',
    'दूसरे पैराग्राफ पर बाहरी (outside) बॉर्डर लगाएँ।',
    ARRAY['Select the second paragraph.', 'Open the Borders menu and choose All Borders.']::text[],
    ARRAY['दूसरे पैराग्राफ को चुनें।', 'बॉर्डर मेन्यू से ऑल बॉर्डर चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":2}}'::jsonb,
    '[{"kind":"border","edge":"all"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    9,
    'word',
    'Paragraph borders',
    'Hard',
    3,
    'Apply an outside border to the second paragraph and set its colour to red.',
    'दूसरे पैराग्राफ पर बाहरी बॉर्डर लगाकर उसका रंग लाल (red) करें।',
    ARRAY['Select the second paragraph.', 'Open Borders and Shading, choose a box border and set the colour to red.']::text[],
    ARRAY['दूसरे पैराग्राफ को चुनें।', 'बॉर्डर्स एंड शेडिंग में बॉक्स बॉर्डर चुनें और रंग लाल करें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":2}}'::jsonb,
    '[{"kind":"border","edge":"all","color":"#ff0000"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    10,
    'word',
    'Line spacing',
    'Hard',
    2,
    'Set the line spacing of the fifth paragraph to exactly 18 pt.',
    'पाँचवें पैराग्राफ की लाइन स्पेसिंग ठीक (exactly) 18pt सेट करें।',
    ARRAY['Select the fifth paragraph.', 'In the Paragraph dialog choose Exactly and type 18 pt.']::text[],
    ARRAY['पाँचवें पैराग्राफ को चुनें।', 'पैराग्राफ डायलॉग में एक्ज़ैक्टली चुनकर 18pt लिखें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":5}}'::jsonb,
    '[{"kind":"lineSpacingAt","mode":"exactly","points":18}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    11,
    'word',
    'Character effects',
    'Medium',
    1,
    'Apply All caps to the first sentence of the fourth paragraph.',
    'चौथे पैराग्राफ के पहले वाक्य पर ऑल कैप्स (All caps) लगाएँ।',
    ARRAY['Select the first sentence of the fourth paragraph.', 'Open the Font dialog and tick All caps.']::text[],
    ARRAY['चौथे पैराग्राफ का पहला वाक्य चुनें।', 'फ़ॉन्ट डायलॉग खोलकर ऑल कैप्स चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"sentence","index":1,"paragraph":4}}'::jsonb,
    '[{"kind":"caps","caps":"all"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    12,
    'word',
    'Character effects',
    'Medium',
    1,
    'Apply Small caps to the first word of the second paragraph.',
    'दूसरे पैराग्राफ के पहले शब्द पर स्मॉल कैप्स (Small caps) लगाएँ।',
    ARRAY['Select the first word of the second paragraph.', 'Open the Font dialog and tick Small caps.']::text[],
    ARRAY['दूसरे पैराग्राफ का पहला शब्द चुनें।', 'फ़ॉन्ट डायलॉग खोलकर स्मॉल कैप्स चुनें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"word","index":1,"paragraph":2}}'::jsonb,
    '[{"kind":"caps","caps":"small"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    13,
    'word',
    'Indentation',
    'Hard',
    2,
    'Give the third paragraph a hanging indent of 0.5 inches.',
    'तीसरे पैराग्राफ को 0.5 इंच का हैंगिंग इंडेंट दें।',
    ARRAY['Select the third paragraph.', 'In the Paragraph dialog choose Hanging and type 0.5".']::text[],
    ARRAY['तीसरे पैराग्राफ को चुनें।', 'पैराग्राफ डायलॉग में हैंगिंग चुनकर 0.5" लिखें।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":3}}'::jsonb,
    '[{"kind":"firstLineIndent","special":"hanging","cm":0.5,"unit":"inch"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    14,
    'word',
    'Lists',
    'Hard',
    3,
    'Apply a numbered list format to the first, second and fourth paragraphs.',
    'पहले, दूसरे और चौथे पैराग्राफ पर क्रमांकित (numbered) सूची लगाएँ।',
    ARRAY['Select the first paragraph and press Numbering.', 'Repeat for the second and the fourth paragraphs.']::text[],
    ARRAY['पहला पैराग्राफ चुनकर नंबरिंग दबाएँ।', 'दूसरे और चौथे पैराग्राफ पर दोहराएँ।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":"all","steps":[{"scope":{"select":"paragraph","index":1},"operations":[{"kind":"list","list":"ordered"}]},{"scope":{"select":"paragraph","index":2},"operations":[{"kind":"list","list":"ordered"}]},{"scope":{"select":"paragraph","index":4},"operations":[{"kind":"list","list":"ordered"}]}]}'::jsonb,
    '[{"kind":"list","list":"ordered"}]'::jsonb
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = 'word-efficiency-test-5'),
    15,
    'word',
    'Lists',
    'Medium',
    1,
    'Change the third paragraph from a numbered list to a bulleted list.',
    'तीसरे पैराग्राफ की क्रमांकित सूची को बुलेट सूची में बदलें।',
    ARRAY['Select the third paragraph.', 'Press Bullets.']::text[],
    ARRAY['तीसरे पैराग्राफ को चुनें।', 'बुलेट्स दबाएँ।']::text[],
    '{"subject":"word","lines":{"en":["The Strategy group will present the quarterly review to every department head on Friday afternoon.","Innovation remains the first measure of progress in each of the four business units this year.","Team leads should collect feedback from their members before the Strategy session begins.","The Innovation award will be announced once the review of all submitted proposals is complete.","Queries about the agenda may be sent to the office of the general manager until Thursday evening."],"hi":["Strategy समूह शुक्रवार अपराह्न प्रत्येक विभागाध्यक्ष के समक्ष तिमाही समीक्षा प्रस्तुत करेगा।","इस वर्ष चारों व्यावसायिक इकाइयों में प्रगति का पहला मापदंड Innovation ही रहेगा।","दल प्रमुख Strategy सत्र आरंभ होने से पूर्व अपने सदस्यों से सुझाव एकत्र करें।","सभी प्राप्त प्रस्तावों की समीक्षा पूर्ण होने पर Innovation पुरस्कार की घोषणा की जाएगी।","कार्यसूची से संबंधित प्रश्न गुरुवार संध्या तक महाप्रबंधक कार्यालय को भेजे जा सकते हैं।"]},"scope":{"select":"paragraph","index":3},"initial":[{"scope":{"select":"paragraph","index":3},"operations":[{"kind":"list","list":"ordered"}]}]}'::jsonb,
    '[{"kind":"list","list":"bullet"}]'::jsonb
  );
