/**
 * Writes the migration that loads the two Word efficiency papers.
 *
 * The papers are TypeScript (`src/exam/papers/wordEfficiency.ts`) because that
 * is what `wordEfficiency.test.ts` marks — every question's worked answer
 * against its own derived key. The SQL is generated from the same source rather
 * than typed beside it, so what ships to the database is what was tested.
 *
 *     npx tsx scripts/generateWordEfficiencyMigration.ts
 *
 * Re-run it after changing a paper, and commit the regenerated file.
 */

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { stepsOf } from '../src/exam/authoring/word';
import { WORD_EFFICIENCY_PAPERS, type WordPaper } from '../src/exam/papers/wordEfficiency';
import type { WordQuestionDraft } from '../src/exam/authoring/types';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../db/migrations/0016_word_efficiency_papers.sql');

/** A Postgres string literal, with quotes doubled. */
function literal(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function json(value: unknown): string {
  return `${literal(JSON.stringify(value))}::jsonb`;
}

/** A `text[]` literal for the solution steps. */
function textArray(values: readonly string[]): string {
  return `ARRAY[${values.map(literal).join(', ')}]::text[]`;
}

/** What the row's `content` column holds: the passage, the selection, the steps. */
function contentOf(draft: WordQuestionDraft): Record<string, unknown> {
  const list = stepsOf(draft);

  return {
    subject: 'word',
    lines: draft.lines,
    scope: draft.scope,
    // Only when the question really has several steps: a one-step question is
    // stored as it always was, so nothing has to know about the other shape.
    ...(list.length > 1 ? { steps: list } : {}),
    ...(draft.initial ? { initial: draft.initial } : {}),
  };
}

function questionRows(paper: WordPaper): string {
  return paper.questions
    .map((draft) => {
      const list = stepsOf(draft);
      // A multi-step question's operations column carries the first step's
      // operations; `content.steps` is what the builders read. Keeping the
      // column populated means the admin list's "what does it ask for" summary
      // has something to show either way.
      const operations = list[0]?.operations ?? [];

      return `  (
    gen_random_uuid(),
    (SELECT id FROM paper WHERE slug = ${literal(paper.slug)}),
    ${draft.number},
    'word',
    ${literal(draft.topic)},
    ${literal(draft.difficulty)},
    ${draft.marks},
    ${literal(draft.instruction.en)},
    ${literal(draft.instruction.hi)},
    ${textArray(draft.solution.en)},
    ${textArray(draft.solution.hi)},
    ${json(contentOf(draft))},
    ${json(operations)}
  )`;
    })
    .join(',\n');
}

function testRow(paper: WordPaper): string {
  return `  (
    gen_random_uuid(),
    (SELECT id FROM host_exam),
    ${literal(paper.name)},
    ${literal(paper.slug)},
    'word',
    ${literal(paper.sectionName)},
    ${literal(paper.tagline)},
    ${paper.durationMinutes},
    ${paper.qualifyingMarks},
    'published'
  )`;
}

export function buildMigrationSql(): string {
  return `-- Word Efficiency Tests 4 and 5.
--
-- Generated by \`scripts/generateWordEfficiencyMigration.ts\` from
-- \`src/exam/papers/wordEfficiency.ts\`, which is what \`wordEfficiency.test.ts\`
-- marks question by question. Edit the paper and regenerate; do not edit this
-- file by hand, or the papers that were tested and the papers that ship stop
-- being the same papers.
--
-- Idempotent: a re-run replaces both papers' questions rather than adding a
-- second copy, and leaves every other paper alone.
--
-- Statements are separated the way drizzle-kit separates them, with the marker
-- it splits a file on. Without those markers the whole file is sent as one
-- query, which node-postgres allows and other drivers do not — and a migration
-- that depends on the driver is a migration that works until it does not.
--
-- The marker is deliberately not written out in this comment: the split is a
-- plain string search, so a comment naming it is cut in half and its second
-- half is fed to Postgres as SQL. That is exactly what happened here once.

-- The papers hang off an exam, and which one decides what the mock list calls
-- them. The oldest *published* exam is the candidate-facing one, so that is
-- preferred; an unpublished one is used only when there is nothing else, and on
-- a fresh database one is created — published, or the papers would be listed
-- under an exam nobody can see.
INSERT INTO exams (id, name, slug, category, organiser_name, description, status)
SELECT
  gen_random_uuid(),
  'SSC CGL',
  'ssc-cgl',
  'SSC',
  'Staff Selection Commission',
  'Combined Graduate Level examination.',
  'published'
WHERE NOT EXISTS (SELECT 1 FROM exams);
--> statement-breakpoint

WITH host_exam AS (
  SELECT id
  FROM exams
  -- Published first, then oldest: false sorts before true, so this reads as
  -- "published before everything else" without naming the statuses twice.
  ORDER BY (status <> 'published'), created_at ASC
  LIMIT 1
),
upserted AS (
  INSERT INTO tests (
    id, exam_id, name, slug, subject, section_name, tagline, duration_minutes, qualifying_marks, status
  )
  VALUES
${WORD_EFFICIENCY_PAPERS.map(testRow).join(',\n')}
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    section_name = EXCLUDED.section_name,
    tagline = EXCLUDED.tagline,
    duration_minutes = EXCLUDED.duration_minutes,
    qualifying_marks = EXCLUDED.qualifying_marks,
    status = EXCLUDED.status,
    updated_at = now()
  RETURNING id, slug
)
SELECT 1 FROM upserted;
--> statement-breakpoint

-- The questions are replaced wholesale: a paper's positions must run 1..n with
-- no gaps, and reconciling them one by one would leave a half-updated paper if
-- anything failed in the middle.
DELETE FROM test_questions
WHERE test_id IN (SELECT id FROM tests WHERE slug IN (${WORD_EFFICIENCY_PAPERS.map((paper) => literal(paper.slug)).join(', ')}));
--> statement-breakpoint

${WORD_EFFICIENCY_PAPERS.map(
  (paper) => `WITH paper AS (SELECT id, slug FROM tests WHERE slug = ${literal(paper.slug)})
INSERT INTO test_questions (
  id, test_id, position, subject, topic, difficulty, marks,
  instruction_en, instruction_hi, solution_en, solution_hi, content, operations
)
VALUES
${questionRows(paper)};`,
).join('\n\n')}
`;
}

/**
 * Written only when this file is run directly, so the migration test can import
 * `buildMigrationSql` and compare it with the checked-in file rather than
 * rewriting it first — a test that fixes its own expectation proves nothing.
 */
if (process.argv[1]?.endsWith('generateWordEfficiencyMigration.ts')) {
  writeFileSync(OUT, buildMigrationSql(), 'utf8');
  process.stdout.write(`wrote ${OUT}\n`);
}
